module.exports = {
  AnnouncementRequest: require('./AnnouncementRequest'),
  AttendeeRequest: require('./AttendeeRequest'),
  AttendeeDecisionRequest: require('./AttendeeDecisionRequest'),
  AccreditedUserCreationRequest: require('./AccreditedUserCreationRequest'),
  BasicAuthRequest: require('./BasicAuthRequest'),
  EcosystemCreationRequest: require('./EcosystemCreationRequest'),
  EventCreationRequest: require('./EventCreationRequest'),
  LocationCreationRequest: require('./LocationCreationRequest'),
  MentorRequest: require('./MentorRequest'),
  JobApplicationRequest: require('./JobApplicationRequest'),
  ProjectRequest: require('./ProjectRequest'),
  ProjectMentorRequest: require('./ProjectMentorRequest'),
  ResetTokenRequest: require('./ResetTokenRequest'),
  ResetPasswordRequest: require('./ResetPasswordRequest'),
  SendListRequest: require('./SendListRequest'),
  UploadRequest: require('./UploadRequest'),
  CheckInRequest: require('./CheckInRequest'),
  RSVPRequest: require('./RSVPRequest'),
  UniversalTrackingRequest: require('./UniversalTrackingRequest'),
  UserContactInfoRequest: require('./UserContactInfoRequest')
};
