CREATE TABLE `users` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `github_handle` VARCHAR(50),
  `email` VARCHAR(255) NOT NULL,
  `password` CHAR(60),
  `created` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  UNIQUE INDEX `github_handle_UNIQUE` (`github_handle` ASC)
);

CREATE TABLE `user_roles` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT UNSIGNED NOT NULL,
  `role` ENUM('ADMIN', 'STAFF', 'MENTOR', 'SPONSOR', 'ATTENDEE', 'VOLUNTEER') NOT NULL,
  `active` TINYINT(1) UNSIGNED NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `fk_users_user_roles_id_idx` (`user_id` ASC),
  CONSTRAINT `fk_users_user_roles_id`
	FOREIGN KEY (`user_id`)
	REFERENCES `users` (`id`)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION);
